create or replace PROCEDURE STP_RN_AEREO (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS
BEGIN

DECLARE
   V_AEREO VARCHAR2(1);
   V_TEMLOCALAEREO INT;

    BEGIN
         SELECT COUNT(*) INTO V_TEMLOCALAEREO
              FROM TGFCAB CAB
              INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
              INNER JOIN TGFLOC LOC ON ITE.CODLOCALORIG = LOC.CODLOCAL
              WHERE LOC.AD_AEREO = 'S'
              AND CAB.NUNOTA = P_NUNOTA;

        IF V_TEMLOCALAEREO > 0 THEN
            P_SUCESSO := 'N';
            P_MENSAGEM := 'MENSAGEM A DEFINIR.';
        ELSE
            P_SUCESSO := 'S';
        END IF;
    END;

END;